import './style.css';
import {createIcons, LayoutGrid, Inbox, PanelsTopLeft, Plus, Square, FolderInput, Sun, Moon, HardDrive, Eye, Lock, Ellipsis, Users, Search, ImagePlus, Quote, Link, ArrowLeft, X, Camera, ExternalLink, Image as ImageIcon, Trash2, MessageCircle} from 'lucide';
const icons={LayoutGrid,Inbox,PanelsTopLeft,Plus,Square,FolderInput,Sun,Moon,HardDrive,Eye,Lock,Ellipsis,Users,Search,ImagePlus,Quote,Link,ArrowLeft,X,Camera,ExternalLink,Image:ImageIcon,Trash2,MessageCircle};
import {initialize,snapshot,action,file,type Board,type Pin} from './data';
import {palette} from './media';
import {exportBoard,importBoard} from './backup';
const root=document.querySelector<HTMLDivElement>('#app')!;
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const icon=(s:string)=>`<i data-lucide="${s}"></i>`;
let state:Awaited<ReturnType<typeof snapshot>>,view='all',query='',filter='all',client=false,selected:Pin|null=null;
const urls=new Map<string,string>();let picked:File|undefined;
let theme=localStorage.getItem('studio-wall-theme')||'dark';document.documentElement.dataset.theme=theme;
const boardNow=()=>state.boards.find(b=>b.id===view);
const pinsFor=(id:string)=>state.pins.filter(p=>p.board_id===id);
const image=(p:Pin)=>p.file_ref?urls.get(p.file_ref):null;
function toast(text:string){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.role='status';el.textContent=text;document.body.append(el);setTimeout(()=>el.remove(),4500);}
async function refresh(){state=await snapshot();for(const p of state.pins)if(p.file_ref&&!urls.has(p.file_ref)){const blob=await file(p.file_ref);if(blob)urls.set(p.file_ref,URL.createObjectURL(blob));}render();}
function chips(p:Pin){return `<div class="swatches">${p.palette.map(c=>`<button type="button" class="swatch" style="background:${esc(c)}" title="Find ${esc(c)}" aria-label="Find colour ${esc(c)}" data-colour="${esc(c)}"></button>`).join('')}</div>`;}
function card(p:Pin){const img=image(p);return `<button class="pin ${img?'':'text-pin'}" data-pin="${p.id}">${img?`<img src="${img}" alt="${esc(p.meta.title||p.note||'Saved inspiration')}" loading="lazy">`:`<div class="idea-content">${icon(p.meta.kind==='link'?'link':'quote')}<p>${esc(p.note||p.meta.title||p.source_url)}</p></div>`}<div class="caption"><strong>${esc(p.meta.title||(p.meta.kind==='idea'?'A thought to keep':'Untitled reference'))}</strong><span>${esc(p.is_own?'My own work':p.source_credit||'Credit not added')}${p.source_url?' · Source ↗':''}</span></div></button>`;}
function render(){const board=boardNow();if(client&&!board)client=false;const inbox=state.boards.find(b=>b.name==='Inbox');const title=board?.name||(view==='boards'?'Your boards':'All inspiration');let pins=board?pinsFor(board.id):state.pins;
 if(query){const q=query.toLowerCase();pins=pins.filter(p=>[p.note,p.meta.title,p.source_credit,...p.tags,...p.palette].join(' ').toLowerCase().includes(q));}
 if(filter!=='all')pins=pins.filter(p=>filter==='images'?p.meta.kind==='image':p.meta.kind!=='image');pins=[...pins].sort((a,b)=>b.created_at.localeCompare(a.created_at));
 root.innerHTML=`<aside class="sidebar"><a class="brand" href="#">STUDIO<span>WALL</span><b>◧</b></a><div class="workspace-label">YOUR CREATIVE SPACE</div><nav>${[['all','layout-grid','All inspiration'],[inbox?.id||'','inbox','Inbox'],['boards','panels-top-left','Boards']].map(([id,ic,n])=>`<button data-nav="${id}" class="nav-item ${view===id?'active':''}">${icon(ic)}${n}${id===inbox?.id?`<small>${pinsFor(id).length}</small>`:''}</button>`).join('')}</nav><div class="section-label">MY BOARDS<button data-action="new-board" aria-label="Create board">${icon('plus')}</button></div><div class="board-nav">${state.boards.filter(b=>b.name!=='Inbox').map(b=>`<button class="nav-item ${view===b.id?'active':''}" data-nav="${b.id}">${icon('square')}<span>${esc(b.name)}</span></button>`).join('')||'<p class="hint">Make room for your next idea.</p>'}</div><div class="sidebar-foot"><button data-action="import">${icon('folder-input')} Import board</button><button data-action="theme">${icon(theme==='dark'?'sun':'moon')} ${theme==='dark'?'Light':'Dark'} mode</button><span>${icon('hard-drive')} Saved on this device</span></div></aside>
 <main><header class="mobile-brand">STUDIO WALL<button data-action="theme" aria-label="Toggle colour theme">${icon(theme==='dark'?'sun':'moon')}</button></header>${client?`<div class="preview-banner">${icon('eye')} Client preview · local demonstration<button data-action="exit-preview">Exit preview</button></div>`:''}<div class="topline"><div><div class="eyebrow">${client?'A BOARD TO EXPLORE TOGETHER':board?'COLLECTION':'COLLECT. CONNECT. CREATE.'}</div><h1>${esc(title)}<span class="private">${icon('lock')} Private</span></h1></div><div class="header-actions">${board&&!client?`<button class="secondary" data-action="board-menu" aria-label="Board options">${icon('ellipsis')}</button><button class="secondary" data-action="share">${icon('users')}<span>Collaborate</span></button>`:''}<button class="primary" data-action="save">${icon('plus')} ${client?'Add reference':'Save'}</button></div></div>
 <p class="intro">${esc(board?.description||(view==='boards'?'Gather references around a project, a palette, or a possibility.':'Images, materials, and ideas worth coming back to.'))}</p>
 ${view==='boards'?`<div class="board-grid">${state.boards.map(b=>{const ps=pinsFor(b.id);const cover=ps.find(p=>p.id===b.cover_pin_id)||ps.find(p=>image(p));return `<article class="board-card"><button data-nav="${b.id}"><div class="board-cover">${cover&&image(cover)?`<img src="${image(cover)}" alt="${esc(b.name)}">`:`${icon('panels-top-left')}<span>${esc(b.name)}</span>`}</div><h3>${esc(b.name)}</h3><p>${ps.length} reference${ps.length===1?'':'s'} · Private</p></button><div class="board-order"><button data-up="${b.id}" aria-label="Move ${esc(b.name)} earlier">${icon('arrow-left')}</button></div></article>`;}).join('')}<button class="new-board-card" data-action="new-board">${icon('plus')}Create a board</button></div>`:`<div class="toolbar"><label class="search">${icon('search')}<input id="search" value="${esc(query)}" placeholder="Search notes, tags or colours" aria-label="Search inspiration"><kbd>/</kbd></label><div class="filters">${[['all','All'],['images','Images'],['ideas','Ideas & links']].map(([id,n])=>`<button data-filter="${id}" class="${filter===id?'chosen':''}">${n}</button>`).join('')}</div><span class="count">${pins.length} reference${pins.length===1?'':'s'}</span></div>${pins.length?`<div class="masonry">${pins.map(card).join('')}</div>`:`<div class="empty"><div class="empty-icon">${icon(query?'search':'image-plus')}</div><h2>${query?'Nothing here yet.':'A little space for your next big idea.'}</h2><p>${query?'Try another note, tag, or palette hex colour.':'Drop an image here, save a link, or jot down a thought. Your collection starts with one reference.'}</p>${!query?'<button class="primary" data-action="save">Save your first reference</button><button class="text-button" data-action="sample">Try a sample board</button>':''}</div>`}`}
 ${client&&board?`<section class="feedback"><div><div class="eyebrow">THE CONVERSATION</div><h2>Thoughts & direction</h2><p>Try the feedback flow here. Comments stay on this device.</p></div><div>${state.feedback.filter(f=>f.board_id===board.id).map(f=>`<article><strong>You <small>Local preview</small></strong><p>${esc(f.text)}</p></article>`).join('')}<form id="feedback-form"><label for="feedback-text">Add a thought</label><textarea id="feedback-text" required placeholder="What speaks to you about this direction?"></textarea><button class="primary">Add comment</button></form></div></section>`:''}<footer class="page-foot">Your inspiration, in one place.<span>Private · Device-local prototype</span></footer></main><nav class="mobile-nav"><button data-nav="all" class="${view==='all'?'active':''}">${icon('layout-grid')}Inspiration</button><button data-nav="boards" class="${view==='boards'?'active':''}">${icon('panels-top-left')}Boards</button><button class="mobile-save" data-action="save">${icon('plus')}Save</button></nav><input id="zip-input" type="file" accept=".zip" hidden><dialog id="modal"></dialog>`;
 bind();createIcons({icons});
}
function show(content:string,wide=false){const d=document.querySelector<HTMLDialogElement>('#modal')!;d.className=wide?'wide':'';d.innerHTML=`<button class="close" aria-label="Close">${icon('x')}</button>${content}`;d.querySelector('.close')!.addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close();});d.showModal();createIcons({icons});return d;}
function options(id?:string){return state.boards.map(b=>`<option value="${b.id}" ${id===b.id?'selected':''}>${esc(b.name)}</option>`).join('');}
function saveDialog(files?:File[]){picked=files?.[0];const d=show(`<div class="dialog-heading"><div class="eyebrow">KEEP SOMETHING GOOD</div><h2>${client?'Add a reference':'Save inspiration'}</h2><p>${client?'Local preview: contributions are saved as you on this device.':'A photo, a link, or a thought. Everything else can wait.'}</p></div><form id="save-form"><label class="upload-zone" for="upload">${icon('image-plus')}<strong id="picked-name">${esc(picked?.name||'Choose images or drop them here')}</strong><span>Photo library · JPEG, PNG, WebP and browser-supported images</span></label><input id="upload" type="file" accept="image/*" multiple hidden><label class="camera-button">${icon('camera')} Take a photo<input id="camera" type="file" accept="image/*" capture="environment" hidden></label><div class="form-row"><label>Title <span>optional</span><input name="title" placeholder="What caught your eye?"></label><label>Board<select name="board_id">${options(boardNow()?.id||state.boards.find(b=>b.name==='Inbox')?.id)}</select></label></div><label>Link · saved as a bookmark<input name="source_url" type="url" placeholder="https://…"></label><label>Note or idea<textarea name="note" rows="3" placeholder="A colour, a texture, a direction to explore…"></textarea></label><div class="form-row"><label>Source / creator credit<input name="source_credit" placeholder="Who made or photographed it?"></label><label>Tags<input name="tags" placeholder="plaster, warm tones, sculpture"></label></div><label class="checkbox"><input type="checkbox" name="is_own"> This is my own work</label><p class="form-help">Private by default. Keep the creator’s credit and original link with references.</p><p class="error" role="alert"></p><button class="primary submit">${icon('plus')} Save to board</button></form>`);
 let batch=files||[];for(const id of ['upload','camera'])d.querySelector<HTMLInputElement>('#'+id)!.onchange=e=>{batch=Array.from((e.target as HTMLInputElement).files||[]);d.querySelector('#picked-name')!.textContent=batch.length>1?`${batch.length} images selected`:batch[0]?.name||'Choose images';};
 d.querySelector<HTMLFormElement>('form')!.onsubmit=async e=>{e.preventDefault();const form=e.target as HTMLFormElement;const submit=form.querySelector<HTMLButtonElement>('.submit')!;submit.disabled=true;try{const values=Object.fromEntries(new FormData(form));const payload={...values,is_own:values.is_own==='on',tags:String(values.tags||'').split(',').map(t=>t.trim()).filter(Boolean)};for(const blob of batch.length?batch:[undefined]){if(blob&&blob.size>25*1024*1024)throw Error('Please use images smaller than 25 MB.');await action({type:'pin.save',payload:{...payload,palette:blob?await palette(blob):[]},blob});}d.close();await refresh();toast('Saved to your board');}catch(e){d.querySelector('.error')!.textContent=(e as Error).message;}finally{submit.disabled=false;}};
}
function focusPin(p:Pin){selected=p;const d=show(`<div class="focus-layout"><div class="focus-image">${image(p)?`<img src="${image(p)}" alt="${esc(p.meta.title||'Saved reference')}">`:`<blockquote>${esc(p.note||p.source_url)}</blockquote>`}</div><div class="inspector"><div class="eyebrow">SAVED INSPIRATION</div><h2>${esc(p.meta.title||'A reference to return to')}</h2>${chips(p)}<form id="edit-form"><label>Title<input name="title" value="${esc(p.meta.title)}"></label><label>Board<select name="board_id">${options(p.board_id)}</select></label><label>Notes<textarea name="note" rows="4">${esc(p.note)}</textarea></label><label>Tags<input name="tags" value="${esc(p.tags.join(', '))}"></label><div class="source-block"><h3>Source & credit</h3><label>Creator / source<input name="source_credit" value="${esc(p.source_credit)}"></label><label>Original link<input name="source_url" type="url" value="${esc(p.source_url)}"></label>${p.source_url?`<a href="${esc(p.source_url)}" target="_blank" rel="noopener noreferrer">View original ${icon('external-link')}</a>`:''}<label class="checkbox"><input type="checkbox" name="is_own" ${p.is_own?'checked':''}> My own work</label></div><p class="error" role="alert"></p><button class="primary submit">Save changes</button></form><div class="pin-actions"><button id="cover">${icon('image')} Use as board cover</button><button id="delete-pin" class="danger">${icon('trash-2')} Delete reference</button></div></div></div>`,true);
 d.querySelector<HTMLFormElement>('form')!.onsubmit=async e=>{e.preventDefault();try{const values=Object.fromEntries(new FormData(e.target as HTMLFormElement));await action({type:'pin.update',id:p.id,payload:{...values,tags:String(values.tags).split(',').map(t=>t.trim()).filter(Boolean),is_own:values.is_own==='on'}});d.close();await refresh();toast('Changes saved');}catch(e){d.querySelector('.error')!.textContent=(e as Error).message;}};
 d.querySelector('#cover')!.addEventListener('click',()=>run(async()=>{await action({type:'board.update',id:p.board_id,payload:{cover_pin_id:p.id}});toast('Board cover updated');}));d.querySelector('#delete-pin')!.addEventListener('click',()=>run(async()=>{if(confirm('Delete this reference? It will be soft-deleted from this device.')){await action({type:'pin.delete',id:p.id});d.close();await refresh();}}));
 d.querySelectorAll<HTMLButtonElement>('[data-colour]').forEach(b=>b.onclick=()=>{query=b.dataset.colour!;view='all';d.close();render();});
}
function boardDialog(board?:Board){const d=show(`<div class="dialog-heading"><div class="eyebrow">A PLACE FOR YOUR IDEAS</div><h2>${board?'Edit board':'Create a board'}</h2></div><form><label>Name<input name="name" required maxlength="100" value="${esc(board?.name)}" placeholder="e.g. A quieter kind of blue"></label><label>Description<textarea name="description" placeholder="What are we exploring?">${esc(board?.description)}</textarea></label><p class="error" role="alert"></p><button class="primary submit">${board?'Save changes':'Create board'}</button></form>${board?'<div class="pin-actions"><button id="export-board">Export board ZIP</button><button class="danger" id="delete-board">Delete board</button></div>':''}`);d.querySelector<HTMLFormElement>('form')!.onsubmit=async e=>{e.preventDefault();try{const b=await action({type:board?'board.update':'board.create',id:board?.id,payload:Object.fromEntries(new FormData(e.target as HTMLFormElement))});view=b.id;d.close();await refresh();}catch(e){d.querySelector('.error')!.textContent=(e as Error).message;}};if(board){d.querySelector('#export-board')!.addEventListener('click',()=>run(()=>exportBoard(board)));d.querySelector('#delete-board')!.addEventListener('click',()=>run(async()=>{if(confirm('Delete this board and its references from this device?')){await action({type:'board.delete',id:board.id});view='all';d.close();await refresh();}}));}}
function shareDialog(){const d=show(`<div class="dialog-heading"><div class="eyebrow">MAKE SPACE FOR COLLABORATION</div><h2>Explore a direction together.</h2><p>Give a client or designer one focused board for references, your artwork, and feedback.</p></div><div class="permission"><span>${icon('eye')} View</span><p>Browse the board and open references.</p></div><div class="permission"><span>${icon('message-circle')} Comment</span><p>Add feedback and discuss a direction.</p></div><div class="permission"><span>${icon('image-plus')} Contribute</span><p>Add images, links, and ideas to this board.</p></div><div class="notice">Shared links and client accounts will connect to your studio backend. This preview stays on this device; it does not create a live link.</div><button class="primary submit" id="client-preview">${icon('eye')} Preview client experience</button>`);d.querySelector('#client-preview')!.addEventListener('click',()=>{client=true;d.close();render();});}
async function run(fn:()=>Promise<unknown>){try{await fn();}catch(e){toast((e as Error).message||'Something went wrong. Please try again.');}}
async function sample(){const response=await fetch('/sample-plaster.webp');if(!response.ok)throw Error('Sample image is not available offline yet.');const sampleBlob=await response.blob();const b=await action({type:'board.create',payload:{name:'A quieter kind of blue',description:'A sample direction: weathered surfaces, soft colour, and traces of warmth.'}});await action({type:'pin.save',blob:sampleBlob,payload:{board_id:b.id,title:'Layers of colour',note:'Illustrative sample image generated for Studio Wall.',source_credit:'AI-generated sample',is_own:false,palette:await palette(sampleBlob),tags:['blue','plaster','texture']}});await action({type:'pin.save',payload:{board_id:b.id,title:'The starting point',note:'Try a pale blue wash over warm plaster. Let the lower layer show through.',tags:['blue','plaster','texture'],is_own:true}});await action({type:'pin.save',payload:{board_id:b.id,title:'A question for the room',note:'Could this feel calm from a distance, but reveal more texture when you come closer?',tags:['direction'],is_own:true}});view=b.id;await refresh();toast('Sample board ready. Add your images to make it yours.');}
function bind(){root.querySelectorAll<HTMLButtonElement>('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav!;query='';client=false;render();});root.querySelectorAll<HTMLButtonElement>('[data-pin]').forEach(b=>b.onclick=()=>focusPin(state.pins.find(p=>p.id===b.dataset.pin)!));root.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter!;render();});
 root.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='save')saveDialog();if(a==='new-board')boardDialog();if(a==='board-menu')boardDialog(boardNow());if(a==='share')shareDialog();if(a==='exit-preview'){client=false;render();}if(a==='theme'){theme=theme==='dark'?'light':'dark';localStorage.setItem('studio-wall-theme',theme);document.documentElement.dataset.theme=theme;render();}if(a==='import')root.querySelector<HTMLInputElement>('#zip-input')!.click();if(a==='sample')run(sample);});
 root.querySelector<HTMLInputElement>('#search')?.addEventListener('input',e=>{const target=e.target as HTMLInputElement;const position=target.selectionStart;query=target.value;render();const n=root.querySelector<HTMLInputElement>('#search')!;n.focus();n.setSelectionRange(position,position);});
 root.querySelector<HTMLInputElement>('#zip-input')!.onchange=e=>run(async()=>{const f=(e.target as HTMLInputElement).files?.[0];if(f){const b=await importBoard(f);view=b.id;await refresh();toast('Board imported');}});
 root.querySelectorAll<HTMLButtonElement>('[data-up]').forEach(b=>b.onclick=()=>run(async()=>{const index=state.boards.findIndex(x=>x.id===b.dataset.up);if(index<1)return;const current=state.boards[index],prev=state.boards[index-1];await action({type:'board.update',id:current.id,payload:{position:prev.position}});await action({type:'board.update',id:prev.id,payload:{position:current.position}});await refresh();}));
 root.querySelector<HTMLFormElement>('#feedback-form')?.addEventListener('submit',e=>{e.preventDefault();run(async()=>{await action({type:'feedback.add',payload:{board_id:view,text:root.querySelector<HTMLTextAreaElement>('#feedback-text')!.value}});await refresh();toast('Comment saved locally');});});
}
document.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();document.body.classList.add('dragging');}});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('dragging');});document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('dragging');const fs=Array.from(e.dataTransfer?.files||[]).filter(f=>f.type.startsWith('image/'));if(fs.length){document.querySelector<HTMLDialogElement>('dialog')?.close();saveDialog(fs);}});
document.addEventListener('paste',e=>{if((e.target as HTMLElement).matches('input,textarea'))return;const fs=Array.from(e.clipboardData?.files||[]);if(fs.length){e.preventDefault();saveDialog(fs);}else{const text=e.clipboardData?.getData('text/plain');if(text&&/^https?:\/\//i.test(text)){saveDialog();document.querySelector<HTMLInputElement>('[name=source_url]')!.value=text;}}});document.addEventListener('keydown',e=>{if(e.key==='/'&&!(e.target as HTMLElement).matches('input,textarea')){e.preventDefault();document.querySelector<HTMLInputElement>('#search')?.focus();}});
async function boot(){try{await initialize();await refresh();if('serviceWorker'in navigator&&import.meta.env.PROD)navigator.serviceWorker.register('/sw.js').catch(()=>toast('Offline setup failed. Reopen while online to try again.'));}catch(e){root.innerHTML=`<div class="empty"><h1>Studio Wall could not open local storage.</h1><p>${esc((e as Error).message)}</p><p>Allow browser storage, then reload.</p></div>`;}}boot();
