import type {Annotation} from './data';

const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const point=(e:PointerEvent,svg:SVGSVGElement)=>{const r=svg.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};};
function shape(a:Annotation){const pts=a.points;if(!pts.length)return '';if(a.tool==='pen')return `<polyline points="${pts.map(p=>`${p.x*1000},${p.y*1000}`).join(' ')}" fill="none" stroke="currentColor" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>`;const s=pts[0],e=pts[pts.length-1];if(a.tool==='circle'){const x=Math.min(s.x,e.x)*1000,y=Math.min(s.y,e.y)*1000,w=Math.abs(e.x-s.x)*1000,h=Math.abs(e.y-s.y)*1000;return `<ellipse cx="${x+w/2}" cy="${y+h/2}" rx="${w/2}" ry="${h/2}" fill="none" stroke="currentColor" stroke-width="8"/>`;}return `<line x1="${s.x*1000}" y1="${s.y*1000}" x2="${e.x*1000}" y2="${e.y*1000}" stroke="currentColor" stroke-width="8" marker-end="url(#arrowhead)"/>`;}
export function annotationOverlay(items:Annotation[]=[]){if(!items.length)return '';return `<svg class="annotation-overlay" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-label="${items.length} saved markups"><defs><marker id="arrowhead" markerWidth="18" markerHeight="18" refX="9" refY="5" orient="auto"><path d="M0,0 L10,5 L0,10 z" fill="currentColor"/></marker></defs>${items.map(shape).join('')}</svg>`;}

export function openMarkup(src:string,initial:Annotation[]=[],save:(items:Annotation[])=>Promise<void>){
 let items=[...initial],tool:Annotation['tool']='pen',draft:Annotation|null=null;
 const d=document.createElement('dialog');d.className='markup-dialog';
 d.innerHTML=`<div class="markup-head"><div><strong>Mark up image</strong><span>Draw, circle, or point to something and attach a note.</span></div><button data-close aria-label="Close">✕</button></div><div class="markup-layout"><div class="markup-image"><img src="${esc(src)}" alt="Image to annotate"><svg class="markup-canvas" viewBox="0 0 1000 1000" preserveAspectRatio="none"><defs><marker id="markup-arrowhead" markerWidth="18" markerHeight="18" refX="9" refY="5" orient="auto"><path d="M0,0 L10,5 L0,10 z" fill="currentColor"/></marker></defs><g class="saved"></g><g class="draft"></g></svg></div><aside><div class="markup-tools"><button data-tool="pen" class="active">Pen</button><button data-tool="circle">Circle</button><button data-tool="arrow">Arrow</button></div><label>Comment about this mark<textarea rows="4" placeholder="What should we notice here?"></textarea></label><button class="primary" data-save disabled>Save mark + note</button><div class="markup-list"></div></aside></div>`;
 document.body.append(d);const svg=d.querySelector<SVGSVGElement>('.markup-canvas')!,saved=d.querySelector<SVGGElement>('.saved')!,draftGroup=d.querySelector<SVGGElement>('.draft')!,note=d.querySelector<HTMLTextAreaElement>('textarea')!,saveBtn=d.querySelector<HTMLButtonElement>('[data-save]')!;
 const draw=()=>{saved.innerHTML=items.map(shape).join('');draftGroup.innerHTML=draft?shape(draft).replace('arrowhead','markup-arrowhead'):'';d.querySelector('.markup-list')!.innerHTML=items.length?items.map((a,i)=>`<article><strong>${a.tool==='pen'?'Drawing':a.tool==='circle'?'Circle':'Arrow'} ${i+1}</strong><p>${esc(a.comment||'No note')}</p><button data-delete="${a.id}">Delete</button></article>`).join(''):'<p class="form-help">No saved marks yet.</p>';d.querySelectorAll<HTMLButtonElement>('[data-delete]').forEach(b=>b.onclick=async()=>{items=items.filter(a=>a.id!==b.dataset.delete);await save(items);draw();});};
 d.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool as Annotation['tool'];d.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));});
 let drawing=false;
 svg.onpointerdown=e=>{drawing=true;svg.setPointerCapture?.(e.pointerId);const p=point(e,svg);draft={id:'mark-'+Date.now(),tool,points:[p],comment:''};draftGroup.innerHTML=shape(draft);saveBtn.disabled=true;};
 svg.onpointermove=e=>{if(!drawing||!draft)return;const p=point(e,svg);if(tool==='pen')draft.points.push(p);else draft.points=[draft.points[0],p];draftGroup.innerHTML=shape(draft).replace('arrowhead','markup-arrowhead');};
 svg.onpointerup=e=>{if(!drawing||!draft)return;drawing=false;if(tool!=='pen')draft.points=[draft.points[0],point(e,svg)];draftGroup.innerHTML=shape(draft).replace('arrowhead','markup-arrowhead');saveBtn.disabled=false;note.focus();};
 saveBtn.onclick=async()=>{if(!draft)return;draft.comment=note.value.trim();items=[...items,draft];draft=null;note.value='';saveBtn.disabled=true;await save(items);draw();};
 d.querySelector<HTMLButtonElement>('[data-close]')!.onclick=()=>d.close();d.addEventListener('close',()=>d.remove(),{once:true});draw();d.showModal();
}